// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOHxeIVod_i2lQVlkemt-I_Uzx6OFeRCQ',
    appId: '1:719308957740:web:40ff2c44e82bb4ca56c989',
    messagingSenderId: '719308957740',
    projectId: 'tiktok-tutorial-872cf',
    authDomain: 'tiktok-tutorial-872cf.firebaseapp.com',
    storageBucket: 'tiktok-tutorial-872cf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWw4eYwTJ_IkCsLeuTt1OnalrvsapHals',
    appId: '1:719308957740:android:00752c5dbfc2e7ec56c989',
    messagingSenderId: '719308957740',
    projectId: 'tiktok-tutorial-872cf',
    storageBucket: 'tiktok-tutorial-872cf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAN6ewtCEfvOxN7Oy_yivO5wPS7E_PlyN8',
    appId: '1:719308957740:ios:c7befd3311db969256c989',
    messagingSenderId: '719308957740',
    projectId: 'tiktok-tutorial-872cf',
    storageBucket: 'tiktok-tutorial-872cf.appspot.com',
    iosBundleId: 'com.abhaytrials.tiktokclone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAN6ewtCEfvOxN7Oy_yivO5wPS7E_PlyN8',
    appId: '1:719308957740:ios:10f2861060c1cf1f56c989',
    messagingSenderId: '719308957740',
    projectId: 'tiktok-tutorial-872cf',
    storageBucket: 'tiktok-tutorial-872cf.appspot.com',
    iosBundleId: 'com.example.tiktokCloneApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOHxeIVod_i2lQVlkemt-I_Uzx6OFeRCQ',
    appId: '1:719308957740:web:8b04a8b45b256e6e56c989',
    messagingSenderId: '719308957740',
    projectId: 'tiktok-tutorial-872cf',
    authDomain: 'tiktok-tutorial-872cf.firebaseapp.com',
    storageBucket: 'tiktok-tutorial-872cf.appspot.com',
  );
}
